sudo: required
language: generic
services:
   - docker
before_install:
   - cd complex/client
   - docker build -t arindam14783/multi-client -f Dockerfile.dev . 

script:
   - docker run -e CI=true arindam14783/multi-client npm test

after_success:
   - cd complex/client
   - docker build -t  arindam14783/multi-client .
   - cd ../nginx
   - docker build -t  arindam14783/multi-nginx .
   - cd ../server
   - docker build -t  arindam14783/multi-server .
   - cd ../worker
   - docker build -t  arindam14783/multi-worker .
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker push arindam14783/multi-client
   - docker push arindam14783/multi-nginx
   - docker push arindam14783/multi-server
   - docker push arindam14783/multi-worker
   - cd ../..

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-716322363208" 
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
