sudo: required
language: generic
services:
   - docker
before_install:
   - cd section6/frontend
   - docker build -t arindam14783/frontendtest -f Dockerfile.dev . 

script:
   - docker run -e CI=true arindam14783/frontendtest npm run test
