sudo: required
language: generic
services:
   - docker
before_install:
   - cd complex/client
   - docker build -t arindam14783/multi-client -f Dockerfile.dev . 

script:
   - docker run -e CI=true arindam14783/multi-client npm test

after_success:
   - cd complex/client
   - docker build -t  arindam14783/multi-client .
   - cd complex/mginx
   - docker build -t  arindam14783/multi-nginx .
   - cd complex/server
   - docker build -t  arindam14783/multi-server .
   - cd complex/worker
   - docker build -t  arindam14783/multi-worker .
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker push arindam14783/multi-client
   - docker push arindam14783/multi-nginx
   - docker push arindam14783/multi-server
   - docker push arindam14783/multi-worker


# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-kuber-complexClient"
#   env: "DockerKuberReact-env"
#   bucket_name: "elasticbeanstalk-us-west-2-716322363208" 
#   bucket_path: "docker-kuber-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
