sudo: required
language: generic
services:
   - docker

before_install:
   - docker build -t arindam14783/frontendtest -f Dockerfile.dev . 

script:
   - docker run -e CI=true arindam14783/frontendtest npm run test
